# Generated by Django 2.2.10 on 2021-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answers',
            field=models.TextField(default='', help_text='Users answer on interview, in json format [answer1, answer2, answer3, ...]', max_length=2000),
        ),
    ]
