# Generated by Django 2.2.10 on 2021-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20210514_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.TextField(default=' ', help_text='Answers to choose if type of question is one answer of many answers', max_length=500, null=True),
        ),
    ]
