# Generated by Django 2.2.10 on 2021-05-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20210514_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='Description',
            new_name='description',
        ),
    ]
