# Generated by Django 2.2.10 on 2021-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20210514_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='start_time',
            field=models.DateTimeField(editable=False, help_text='Time when interview starts'),
        ),
    ]
