# Generated by Django 2.2.10 on 2021-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_auto_20210514_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='start_time',
            field=models.DateTimeField(help_text='Time when interview starts'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.TextField(default='', help_text='Answers to choose if type of question is one answer of many answers', max_length=500, null=True),
        ),
    ]
