# Generated by Django 2.2.10 on 2021-05-14 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0007_auto_20210514_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='token',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(help_text='Token of user who answered', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
